language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-22
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew