language: android
android:
  components:
    - tools
    - build-tools-19.1.0
    - android-19
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew